[package]
name = "mboxhisto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mailbox = "0.2"
clap = { version ="3.0", features = ["derive"] }
anyhow = "1.0"
regex = "1.5"
